import json

# Grouping Kids frames into products
kids_products = [
  {
    "id": "lens-s-world-celica-flex-kids-pink",
    "name": "LENS S WORLD Celica Flex Kids (Pink / Black)",
    "type": "eyeglasses",
    "shape": "Rectangle",
    "img": "images/products/kids/kid_frame_1.jpg",
    "gallery": [
      "images/products/kids/kid_frame_1.jpg",
      "images/products/kids/kid_frame_2.jpg"
    ],
    "color": "Translucent Pink",
    "colors": ["Translucent Pink", "Black / Pink"],
    "material": "Swiss TR90 Memory Polymer",
    "price": 899,
    "mrp": 1599,
    "brand": "LENS S WORLD",
    "cats": ["kids", "unisex"],
    "sku": "LSW-KID-001",
    "stock": 18,
    "rating": 4.9,
    "reviews": 32,
    "isNew": True,
    "bestSeller": True,
    "size": "Kids Medium (45-20-131)",
    "weight": "14g",
    "description": "Ultra-flexible lightweight kids eyeglasses frame with soft silicone ergonomic temples and shock-resistant TR90 construction.",
    "features": [
      "Unbreakable Flexible TR90 Construction",
      "Soft Cushioned Temple Tips",
      "Skin-Friendly Hypoallergenic Material",
      "Compatible with Blue Cut & Prescription Lenses"
    ],
    "frameOnlyAvailable": True,
    "prescriptionAvailable": True,
    "lensOptionsAvailable": True
  },
  {
    "id": "lens-s-world-seco-junior-magenta",
    "name": "LENS S WORLD Seco Junior Oval (Magenta / White)",
    "type": "eyeglasses",
    "shape": "Oval",
    "img": "images/products/kids/kid_frame_3.jpg",
    "gallery": [
      "images/products/kids/kid_frame_3.jpg",
      "images/products/kids/kid_frame_4.jpg"
    ],
    "color": "Vibrant Magenta",
    "colors": ["Vibrant Magenta", "White Trim"],
    "material": "Dual-Tone Flexible Polymer",
    "price": 949,
    "mrp": 1699,
    "brand": "LENS S WORLD",
    "cats": ["kids"],
    "sku": "LSW-KID-002",
    "stock": 14,
    "rating": 4.8,
    "reviews": 27,
    "isNew": True,
    "bestSeller": False,
    "size": "Kids Small (46-16-125)",
    "weight": "13g",
    "description": "Ergonomically contoured oval kids frame designed for maximum durability during school, study, and outdoor play.",
    "features": [
      "Dual-Tone Sculpted Frame Design",
      "Flexible Comfort-Fit Hinges",
      "Zero-Pressure Nose Bridge",
      "Scratch Guard Resistant Finish"
    ],
    "frameOnlyAvailable": True,
    "prescriptionAvailable": True,
    "lensOptionsAvailable": True
  },
  {
    "id": "lens-s-world-play-active-kids-blue",
    "name": "LENS S WORLD Active Play Kids (Cobalt / Cyan)",
    "type": "eyeglasses",
    "shape": "Rectangle",
    "img": "images/products/kids/kid_frame_5.jpg",
    "gallery": [
      "images/products/kids/kid_frame_5.jpg",
      "images/products/kids/kid_frame_6.jpg",
      "images/products/kids/kid_frame_7.jpg"
    ],
    "color": "Cobalt Blue",
    "colors": ["Cobalt Blue", "Cyan"],
    "material": "High-Impact Memory TR90",
    "price": 899,
    "mrp": 1499,
    "brand": "LENS S WORLD",
    "cats": ["kids"],
    "sku": "LSW-KID-003",
    "stock": 20,
    "rating": 4.9,
    "reviews": 41,
    "isNew": False,
    "bestSeller": True,
    "size": "Kids Standard (47-16-128)",
    "weight": "15g",
    "description": "All-day comfortable rectangle kids spectacles crafted with flexible memory polymer that bounces back from bends and twists.",
    "features": [
      "Memory Flex Technology",
      "Impact Resistant Standard",
      "Anti-Slip Ergonomic Temple Grip",
      "Full Prescription Customization"
    ],
    "frameOnlyAvailable": True,
    "prescriptionAvailable": True,
    "lensOptionsAvailable": True
  },
  {
    "id": "lens-s-world-pastel-pop-kids-violet",
    "name": "LENS S WORLD Pastel Pop Kids Round (Lilac Violet)",
    "type": "eyeglasses",
    "shape": "Round",
    "img": "images/products/kids/kid_frame_8.jpg",
    "gallery": [
      "images/products/kids/kid_frame_8.jpg",
      "images/products/kids/kid_frame_9.jpg",
      "images/products/kids/kid_frame_10.jpg"
    ],
    "color": "Lilac Violet",
    "colors": ["Lilac Violet", "Pastel Pink"],
    "material": "Hypoallergenic Swiss TR90",
    "price": 999,
    "mrp": 1799,
    "brand": "LENS S WORLD",
    "cats": ["kids"],
    "sku": "LSW-KID-004",
    "stock": 16,
    "rating": 5.0,
    "reviews": 38,
    "isNew": True,
    "bestSeller": True,
    "size": "Kids Compact (45-18-125)",
    "weight": "13g",
    "description": "Trendy round pastel frame for kids with ultra-smooth edges and featherweight construction for extended screen and reading comfort.",
    "features": [
      "Featherlight 13g Profile",
      "Chic Round Contour Design",
      "Gentle Anti-Pinch Hinges",
      "Prescription & Blue-Cut Ready"
    ],
    "frameOnlyAvailable": True,
    "prescriptionAvailable": True,
    "lensOptionsAvailable": True
  },
  {
    "id": "lens-s-world-speedster-kids-sport",
    "name": "LENS S WORLD Speedster Kids Sport (Crimson / Slate)",
    "type": "eyeglasses",
    "shape": "Rectangle",
    "img": "images/products/kids/kid_frame_11.jpg",
    "gallery": [
      "images/products/kids/kid_frame_11.jpg"
    ],
    "color": "Crimson Red",
    "colors": ["Crimson Red", "Slate Black"],
    "material": "High-Grade Flexible TR90",
    "price": 949,
    "mrp": 1649,
    "brand": "LENS S WORLD",
    "cats": ["kids"],
    "sku": "LSW-KID-005",
    "stock": 15,
    "rating": 4.8,
    "reviews": 19,
    "isNew": False,
    "bestSeller": False,
    "size": "Kids Medium (46-17-130)",
    "weight": "15g",
    "description": "Sporty rectangle spectacles engineered for active children with textured temple grips and high torsional flexibility.",
    "features": [
      "Sport-Fit Grip Temples",
      "Reinforced Front Bridge",
      "Drop-Proof Durability",
      "Prescription Compatible"
    ],
    "frameOnlyAvailable": True,
    "prescriptionAvailable": True,
    "lensOptionsAvailable": True
  }
]

# Grouping Womens frames into products
womens_products = [
  {
    "id": "lens-s-world-texaas-crystal-cat-eye",
    "name": "LENS S WORLD Texaas Crystal Cat-Eye (Blush Pink)",
    "type": "eyeglasses",
    "shape": "Cat-Eye",
    "img": "images/products/womens/women_frame_1.jpg",
    "gallery": [
      "images/products/womens/women_frame_1.jpg",
      "images/products/womens/women_frame_2.jpg",
      "images/products/womens/women_frame_3.jpg",
      "images/products/womens/women_frame_4.jpg"
    ],
    "color": "Blush Pink Crystal",
    "colors": ["Blush Pink Crystal", "Purple Accents"],
    "material": "Handcrafted Crystal Italian Acetate",
    "price": 1499,
    "mrp": 2499,
    "brand": "LENS S WORLD",
    "cats": ["women"],
    "sku": "LSW-WMN-001",
    "stock": 22,
    "rating": 4.9,
    "reviews": 64,
    "isNew": True,
    "bestSeller": True,
    "size": "Medium (50-18-145)",
    "weight": "19g",
    "description": "Stunning transparent blush pink cat-eye frame featuring dual-tone temple arms and premium hand-polished acetate contours.",
    "features": [
      "Handcrafted Crystal Acetate",
      "Feminine Cat-Eye Browline",
      "Smooth 5-Barrel Steel Hinges",
      "Fits All Single Vision & Progressive Lenses"
    ],
    "frameOnlyAvailable": True,
    "prescriptionAvailable": True,
    "lensOptionsAvailable": True
  },
  {
    "id": "lens-s-world-ame-lady-round-chic",
    "name": "LENS S WORLD Ame Lady Round Chic (Translucent Rose)",
    "type": "eyeglasses",
    "shape": "Round",
    "img": "images/products/womens/women_frame_5.jpg",
    "gallery": [
      "images/products/womens/women_frame_5.jpg",
      "images/products/womens/women_frame_6.jpg",
      "images/products/womens/women_frame_7.jpg",
      "images/products/womens/women_frame_8.jpg"
    ],
    "color": "Translucent Rose",
    "colors": ["Translucent Rose", "Gold Metal Core"],
    "material": "Ultra-Lightweight Gloss Acetate",
    "price": 1399,
    "mrp": 2299,
    "brand": "LENS S WORLD",
    "cats": ["women"],
    "sku": "LSW-WMN-002",
    "stock": 19,
    "rating": 4.8,
    "reviews": 51,
    "isNew": True,
    "bestSeller": True,
    "size": "Medium (51-17-142)",
    "weight": "18g",
    "description": "Elegant round-oval silhouette in transparent rose gloss with engraved gold metal temple cores for effortless daily sophistication.",
    "features": [
      "Featherlight Gloss Finish",
      "Reinforced Core Wire Temples",
      "Ergonomic Saddle Bridge",
      "Full Prescription Customization"
    ],
    "frameOnlyAvailable": True,
    "prescriptionAvailable": True,
    "lensOptionsAvailable": True
  },
  {
    "id": "lens-s-world-wonder-turf-crystal-mint",
    "name": "LENS S WORLD Wonder Turf Crystal Pantos (Ice Mint)",
    "type": "eyeglasses",
    "shape": "Round",
    "img": "images/products/womens/women_frame_12.jpg",
    "gallery": [
      "images/products/womens/women_frame_12.jpg",
      "images/products/womens/women_frame_13.jpg",
      "images/products/womens/women_frame_14.jpg",
      "images/products/womens/women_frame_15.jpg"
    ],
    "color": "Ice Mint Crystal",
    "colors": ["Ice Mint Crystal", "Silver Core"],
    "material": "Crystal Clear TR90 Acetate Hybrid",
    "price": 1599,
    "mrp": 2599,
    "brand": "LENS S WORLD",
    "cats": ["women", "unisex"],
    "sku": "LSW-WMN-003",
    "stock": 17,
    "rating": 5.0,
    "reviews": 73,
    "isNew": True,
    "bestSeller": True,
    "size": "Universal (49-21-140)",
    "weight": "17g",
    "description": "Modern crystal clear ice-mint pantos eyewear offering a luminous contemporary aesthetic with keyhole bridge styling.",
    "features": [
      "Classic Keyhole Nose Bridge",
      "Crystal Ice Hue Transparency",
      "Ultra-Durable Wire Core Arms",
      "Prescription & Screen Ready"
    ],
    "frameOnlyAvailable": True,
    "prescriptionAvailable": True,
    "lensOptionsAvailable": True
  },
  {
    "id": "lens-s-world-elegance-butterfly-gold",
    "name": "LENS S WORLD Elegance Butterfly (Champagne Gold)",
    "type": "eyeglasses",
    "shape": "Butterfly",
    "img": "images/products/womens/women_frame_18.jpg",
    "gallery": [
      "images/products/womens/women_frame_18.jpg",
      "images/products/womens/women_frame_19.jpg",
      "images/products/womens/women_frame_20.jpg"
    ],
    "color": "Champagne Gold",
    "colors": ["Champagne Gold", "Tortoise Temple Tips"],
    "material": "Corrosion-Resistant Metal Alloy",
    "price": 1799,
    "mrp": 2999,
    "brand": "LENS S WORLD",
    "cats": ["women"],
    "sku": "LSW-WMN-004",
    "stock": 12,
    "rating": 4.9,
    "reviews": 46,
    "isNew": False,
    "bestSeller": True,
    "size": "Medium to Large (52-17-142)",
    "weight": "16g",
    "description": "Luxurious butterfly metal frame with subtle geometric angles and cushioned silicone nose pads for executive elegance.",
    "features": [
      "Sculpted Butterfly Geometry",
      "Hypoallergenic Silicone Pads",
      "Polished Champagne Luster",
      "Prescription & Transition Ready"
    ],
    "frameOnlyAvailable": True,
    "prescriptionAvailable": True,
    "lensOptionsAvailable": True
  },
  {
    "id": "lens-s-world-grace-hexagonal-rosegold",
    "name": "LENS S WORLD Grace Hexagonal Metal (Rose Gold)",
    "type": "eyeglasses",
    "shape": "Geometric",
    "img": "images/products/womens/women_frame_24.jpg",
    "gallery": [
      "images/products/womens/women_frame_24.jpg",
      "images/products/womens/women_frame_25.jpg",
      "images/products/womens/women_frame_26.jpg"
    ],
    "color": "Rose Gold",
    "colors": ["Rose Gold", "Clear Tips"],
    "material": "Featherlight Stainless Steel Alloy",
    "price": 1699,
    "mrp": 2799,
    "brand": "LENS S WORLD",
    "cats": ["women"],
    "sku": "LSW-WMN-005",
    "stock": 15,
    "rating": 4.8,
    "reviews": 58,
    "isNew": True,
    "bestSeller": True,
    "size": "Medium (51-19-140)",
    "weight": "15g",
    "description": "Minimalist hexagonal wireframe eyewear in warm rose gold, balancing architectural sharpness with delicate feminine lines.",
    "features": [
      "Geometric Hexagonal Profile",
      "Featherweight 15g Frame",
      "Comfort-Cushioned Bridge",
      "Supports All Prescription Powers"
    ],
    "frameOnlyAvailable": True,
    "prescriptionAvailable": True,
    "lensOptionsAvailable": True
  },
  {
    "id": "lens-s-world-stella-sculpted-burgundy",
    "name": "LENS S WORLD Stella Sculpted Browline (Burgundy / Blush)",
    "type": "eyeglasses",
    "shape": "Cat-Eye",
    "img": "images/products/womens/women_frame_30.jpg",
    "gallery": [
      "images/products/womens/women_frame_30.jpg",
      "images/products/womens/women_frame_31.jpg",
      "images/products/womens/women_frame_32.jpg"
    ],
    "color": "Deep Burgundy",
    "colors": ["Deep Burgundy", "Blush Pink"],
    "material": "Sculpted TR90 Memory Polymer",
    "price": 1449,
    "mrp": 2399,
    "brand": "LENS S WORLD",
    "cats": ["women"],
    "sku": "LSW-WMN-006",
    "stock": 18,
    "rating": 4.9,
    "reviews": 39,
    "isNew": False,
    "bestSeller": False,
    "size": "Medium (52-16-140)",
    "weight": "17g",
    "description": "Deep burgundy and blush gradient cat-eye frame designed to add warmth and definition to facial features.",
    "features": [
      "Two-Tone Gradient Browline",
      "Shatterproof TR90 Flexibility",
      "Pressure-Free Temple Fit",
      "Single Vision & Bifocal Compatible"
    ],
    "frameOnlyAvailable": True,
    "prescriptionAvailable": True,
    "lensOptionsAvailable": True
  },
  {
    "id": "lens-s-world-aura-minimalist-mauve",
    "name": "LENS S WORLD Aura Minimalist Square (Smoky Mauve)",
    "type": "eyeglasses",
    "shape": "Square",
    "img": "images/products/womens/women_frame_36.jpg",
    "gallery": [
      "images/products/womens/women_frame_36.jpg",
      "images/products/womens/women_frame_37.jpg",
      "images/products/womens/women_frame_38.jpg"
    ],
    "color": "Smoky Mauve",
    "colors": ["Smoky Mauve", "Translucent Violet"],
    "material": "High-Grade Transparent Bio-Acetate",
    "price": 1549,
    "mrp": 2499,
    "brand": "LENS S WORLD",
    "cats": ["women"],
    "sku": "LSW-WMN-007",
    "stock": 20,
    "rating": 4.7,
    "reviews": 42,
    "isNew": True,
    "bestSeller": False,
    "size": "Large (53-17-145)",
    "weight": "20g",
    "description": "Subtly oversized square eyewear frame in sophisticated smoky mauve crystal with softly rounded corners.",
    "features": [
      "Oversized Flattering Square",
      "Crystal Mauve Tint Finish",
      "Smooth 5-Barrel Steel Hinges",
      "Prescription Ready"
    ],
    "frameOnlyAvailable": True,
    "prescriptionAvailable": True,
    "lensOptionsAvailable": True
  },
  {
    "id": "lens-s-world-vogue-vintage-caramel",
    "name": "LENS S WORLD Vogue Vintage Oval (Caramel Tortoise)",
    "type": "eyeglasses",
    "shape": "Oval",
    "img": "images/products/womens/women_frame_41.jpg",
    "gallery": [
      "images/products/womens/women_frame_41.jpg",
      "images/products/womens/women_frame_42.jpg",
      "images/products/womens/women_frame_43.jpg",
      "images/products/womens/women_frame_44.jpg"
    ],
    "color": "Caramel Tortoise",
    "colors": ["Caramel Tortoise", "Warm Amber"],
    "material": "Hand-Polished Italian Acetate",
    "price": 1649,
    "mrp": 2699,
    "brand": "LENS S WORLD",
    "cats": ["women"],
    "sku": "LSW-WMN-008",
    "stock": 16,
    "rating": 4.9,
    "reviews": 55,
    "isNew": False,
    "bestSeller": True,
    "size": "Medium (50-19-142)",
    "weight": "19g",
    "description": "Vintage 90s inspired caramel demi oval eyewear with rich warm tones and smooth organic contours.",
    "features": [
      "Rich Amber Tortoise Pattern",
      "Hand-Polished Silk Finish",
      "Universal Ergonomic Fit",
      "Prescription Compatible"
    ],
    "frameOnlyAvailable": True,
    "prescriptionAvailable": True,
    "lensOptionsAvailable": True
  }
]

print(f"Generated {len(kids_products)} Kids products and {len(womens_products)} Womens products.")
